name: Deployment
on:
  push:
    branches:
      - main


jobs:
  Deploy:
    name: Deploy branch main
    runs-on: ubuntu-latest
    steps:
      - name: appleboy-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd app
            git checkout â€” *
            git checkout main
            git pull origin main