name: Deployment
on:
  push:
    branches:
      - main


jobs:
  Deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: verify credentials
          run: aws s3 ls

        - name: set up python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        
        - name: Install dependencies
          run: |
            cd infrastructure/app
            pip install -r requirements.txt -t .


        - name: Zip the code
          run: |
            cd infrastructure/app 
            zip -r ../../deployment-package.zip .

        - name: Upload to s3
          run: |
            aws s3 cp deployment-package.zip s3://file-upload21225/deployment-package.zip
        
        - name: Deploy lambda
          run: |
            aws lambda update-function-code \
            --function-name lambda \
            --s3-bucket file-upload21225 \
            --s3-key deployment-package.zip